FROM node:12-alpine3.12

ENV SKIP_PREFLIGHT_CHECK=true

WORKDIR /var/www/client
ENV PATH=/var/www/client/node_modules/.bin:$PATH

COPY ./client/package.json ./client/yarn.lock ./
COPY ./client/build ./

# Node Entrypoint
COPY docker-react.sh /usr/bin
RUN chmod +x /usr/bin/docker-react.sh
ENTRYPOINT [ "docker-react.sh" ]